import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-6 border-b px-4">
          <Link href="/" className="text-blue-600 text-3xl">
            Home
          </Link>
          <Link href={`/zod`} className="text-blue-600 text-3xl ml-5">
            Zod
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
